/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ISP;

import DIP.Control;
import DIP.TV;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        FrontEndProjectDevelopment frontEnd= new FrontEndProjectDevelopment();
        frontEnd.BuildFrontEnd();
        TV tv=new TV();
        Control DeviceControl= new Control(tv);
        DeviceControl.start();


    }

    public static ArrayList<Integer> intersectionBetweenTwoArray(ArrayList<Integer> arrayList1,ArrayList<Integer> arrayList2){
        ArrayList<Integer> result=new ArrayList<Integer>();

        for (Integer number:arrayList1) {

            if(arrayList2.contains(number))
            {
                result.add(number);
            }
        }
        return result;
    }
}
