/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Observer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
StudentInterface suu1=new Student("STU1");
StudentInterface suu2=new Student("STU2");
StudentInterface suu3=new Student("STU3");
Course JAVA=new Course("java");
JAVA.subscribe(suu1);
JAVA.subscribe(suu2);
JAVA.subscribe(suu3);
JAVA.unSubscribe(suu1);
JAVA.setAvailability(false);

    }
}
