/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Signleton;

import java.util.Arrays;
import java.util.List;

public class App {
    public int getGreeting() {
        return this.hashCode();
    }

    public static void main(String[] args) {
        System.out.println(Singleton.getMyList());// before create instance
      Singleton.getInstance();
        System.out.println(Singleton.getMyList());// after create instance
        System.out.println(Singleton.getMyList());// before create instance
        // you can see that the order of list changed after create instance, and it fixed because  we create just one instance
    }
}
