/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LiskovSubstitution;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Bird GoldenEagle=new Eagle("golden");


    }
}
