/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Factory;

import Factory.superClassVersion.products;
import Factory.superClassVersion.theFactory;
import Factory.interfaceVersion.*;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
// using super class
       products podcast= theFactory.productsFactory("A");
       podcast.deletes();

       // using interface

        Factory.interfaceVersion.products MYprodact= Factory.interfaceVersion.theFactory.Productfactory("B");
        MYprodact.deletes();

    }
}
